=== MashaMl/Homework3WebServicesTask5/src/main/java/HW3/greenhouse.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="greenhouse" type="greenhouseType"/>

  <xs:complexType name="medium_sizeType">
    <xs:simpleContent>
      <xs:extension base="xs:integer">
        <xs:attribute type="xs:string" name="unit" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="visual_parametersType">
    <xs:sequence>
      <xs:element name="stem_color" type="xs:string" />
      <xs:element name="leafs_color" type="xs:string"/>
      <xs:element name="medium_size" type="medium_sizeType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="temperatureType">
    <xs:simpleContent>
      <xs:extension base="xs:integer">
        <xs:attribute type="xs:string" name="unit" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="wateringType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="unit" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="growing_tipsType">
    <xs:sequence>
      <xs:element name="temperature" type="temperatureType"/>

      <xs:element name="lighting">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Light-loving"/>
            <xs:enumeration value="Not light-loving"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>

      <xs:element name="watering" type="wateringType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="plantType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="soil" type="xs:string"/>
      <xs:element name="origin" type="xs:string"/>
      <xs:element type="visual_parametersType" name="visual_parameters"/>
      <xs:element type="growing_tipsType" name="growing_tips"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="greenhouseType">
    <xs:sequence>
      <xs:element type="plantType" name="plant" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== MashaMl/Homework3WebServicesTask5/src/main/java/HW3/greenhouse.xml
<?xml version="1.0" encoding="UTF-8" ?>
<greenhouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="greenhouse.xsd">
    <plant>
        <name>Plant1</name>
        <soil>Black soil</soil>
        <origin>Ukraine</origin>
        <visual_parameters>
            <stem_color>Brown</stem_color>
            <leafs_color>Light green</leafs_color>
            <medium_size unit="meter">2</medium_size>
        </visual_parameters>
        <growing_tips>
            <temperature unit="celsius">15</temperature>
            <lighting>Light-loving</lighting>
            <watering unit="ml/week">600</watering>
        </growing_tips>
    </plant>
    <plant>
        <name>Plant2</name>
        <soil>Black soil</soil>
        <origin>America</origin>
        <visual_parameters>
            <stem_color>Brown</stem_color>
            <leafs_color>Dark green</leafs_color>
            <medium_size unit="meter">3</medium_size>
        </visual_parameters>
        <growing_tips>
            <temperature unit="celsius">25</temperature>
            <lighting>Not light-loving</lighting>
            <watering unit="ml/week">500</watering>
        </growing_tips>
    </plant>
    <plant>
        <name>Plant3</name>
        <soil>Red soil</soil>
        <origin>Uganda</origin>
        <visual_parameters>
            <stem_color>Red</stem_color>
            <leafs_color>Rose</leafs_color>
            <medium_size unit="meter">1</medium_size>
        </visual_parameters>
        <growing_tips>
            <temperature unit="celsius">30</temperature>
            <lighting>Light-loving</lighting>
            <watering unit="ml/week">500</watering>
        </growing_tips>
    </plant>
</greenhouse>
